services:
  nginx:
    container_name: ${CONTAINER_NAME_WEB:-web-toollab}
    image: nginx:stable-alpine3.21-perl
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/prod.conf.template:/etc/nginx/templates/default.conf.template
    depends_on:
      - api
    networks:
      - web

  api:
    container_name: ${CONTAINER_NAME_API:-api-toollab}
    image: php_toollab
    build:
      context: ./docker/php/
      target: dev
    volumes:
      - ./:/var/www
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - web

  db:
    container_name: ${CONTAINER_NAME_DB:-db-toollab}
    image: mariadb:10.11
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web
      
  maildev:
    image: maildev/maildev
    profiles: ["dev"]
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  web:
    driver: bridge

volumes:
  db_data: