services:
  nginx:
    container_name: ${CONTAINER_NAME_WEB:-web-toollab}
    image: nginx:stable-alpine3.21-perl
    env_file: .env
    ports:
      - "${CONTAINER_PORT_WEB}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/prod.conf.template:/etc/nginx/templates/default.conf.template
    depends_on:
      - api
    networks:
      - toollab_network

  api:
    container_name: ${CONTAINER_NAME_API:-api-toollab}
    image: php_toollab
    build:
      context: ./docker/php/
      target: dev
      args:
        - CURRENT_USER=${CURRENT_USER}
        - CURRENT_UID=${CURRENT_UID}
        - TZ=${TZ}
    volumes:
      - ./:/var/www
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - toollab_network

  db:
    container_name: ${CONTAINER_NAME_DB:-db-toollab}
    image: mariadb:11.4.5
    restart: unless-stopped
    ports:
      - "${CONTAINER_PORT_DB}:3306"
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
    volumes:
      - persistent_db:/var/lib/mysql
    networks:
      - toollab_network

  maildev:
    image: maildev/maildev
    container_name: ${CONTAINER_NAME_MAILDEV:-maildev}
    profiles: ["dev"]
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - toollab_network

networks:
  toollab_network:
    external: true
    name: ${NETWORK_NAME}

volumes:
  persistent_db:
    name: ${DB_VOLUME_NAME:-db_data}
    driver: local
