services:
  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_toollab.rule=Host(`api.toollab.fr`)"
      - "traefik.http.routers.web_toollab.entrypoints=web,websecure"
      - "traefik.http.routers.web_toollab.tls=true"
      - "traefik.http.routers.web_toollab.tls.certresolver=myresolver"
      - "traefik.http.middlewares.web_toollab-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.web_toollab.middlewares=web_toollab-redirect"
  api:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: prod

networks:
  web:
    external: true