- name: Deploy to server via SSH
  uses: appleboy/ssh-action@v0.1.6
  with:
    host: ${{ secrets.SERVER_HOST }}
    username: ${{ secrets.SERVER_USER }}
    key: ${{ secrets.SERVER_SSH_KEY }}
    port: 22
    script: |
      echo "⚙️ Manual deploy to ${{ github.event.inputs.environment }}"

      TARGET_DIR="/home/githubdev/${{ github.event.inputs.environment }}/api"

      echo "🚀 Syncing code to $TARGET_DIR ..."
      rsync -avz --delete --exclude=".git*" --exclude=".github" ./ $TARGET_DIR/