name: Manual Deploy to Server

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "⚙️ Manual deploy to ${{ github.event.inputs.environment }}"

            if [ "${{ github.event.inputs.environment }}" = "staging" ]; then
              TARGET_DIR="/home/githubdev/staging/api"
            elif [ "${{ github.event.inputs.environment }}" = "production" ]; then
              TARGET_DIR="/home/githubdev/production/api"
            else
              echo "⛔ Unknown environment. Exiting."
              exit 1
            fi

            echo "🚀 Syncing code to $TARGET_DIR ..."
            rsync -avz --delete --exclude=".git*" --exclude=".github" ./ $TARGET_DIR/