name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment (dev or prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
              echo "Deploying to DEV..."
              rsync -avz --delete --exclude=".git*" --exclude=".github" ./ /home/githubdev/staging/api
            else
              echo "Deploying to PROD..."
              rsync -avz --delete --exclude=".git*" --exclude=".github" ./ /home/githubdev/production/api
            fi