name: Deploy to Server

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync files to the server (no git)
        uses: burnett01/rsync-deployments@v2.0.0
        with:
          switches: -avz --delete --exclude=".git*" --exclude=".github"
          path: ./
          remote_path: ${{ github.ref == 'refs/heads/dev' && '/home/githubdev/staging/api' || '/home/githubdev/production/api' }}
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}