name: Auto Deploy to Server

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "⚙️ Deploying branch: ${{ github.ref_name }}"

            if [ "${{ github.ref_name }}" = "dev" ]; then
              echo "🚀 Deploying to STAGING..."

              # Clean the existing directory to avoid nesting issues
              rm -rf /home/githubdev/staging/api/*

              # Sync the content of the repo (no .git, no .github)
              rsync -avz --delete --exclude=".git*" --exclude=".github" ./ /home/githubdev/staging/api/

            elif [ "${{ github.ref_name }}" = "main" ]; then
              echo "🚀 Deploying to PRODUCTION..."

              # Clean the existing directory to avoid nesting issues
              rm -rf /home/githubdev/production/api/*

              # Sync the content of the repo (no .git, no .github)
              rsync -avz --delete --exclude=".git*" --exclude=".github" ./ /home/githubdev/production/api/

            else
              echo "⛔ Not a deployable branch. Skipping."
            fi